name: Deploy PHP to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl

      - name: Install PHP dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Package Lambda
        run: |
          mkdir package
          cp -r src/* package/ || true
          cp -r public package/ || true
          cp -r vendor package/
          cp index.php package/
          cd package
          zip -r ../function.zip .

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda code
        run: |
          aws lambda update-function-code \
            --function-name my-php-fn \
            --zip-file fileb://function.zip

      - name: Attach Bref layer (PHP 8.1 FPM)
        run: |
          aws lambda update-function-configuration \
            --function-name my-php-fn \
            --runtime provided.al2 \
            --handler index.php \
            --layers arn:aws:lambda:${{ secrets.AWS_REGION }}:209497400698:layer:php-81-fpm:41
